# Generated by Django 5.1.3 on 2024-11-18 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hp', models.CharField(max_length=15, unique=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('PENGGUNA', 'Pengguna'), ('PEKERJA', 'Pekerja')], default='PENGGUNA', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
