# Generated by Django 5.1.3 on 2024-11-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='link_foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='nama_bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='nomor_rekening',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='npwp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
