# Generated by Django 5.1.3 on 2024-11-18 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pekerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SesiLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pemesanan', models.DateField()),
                ('kode_diskon', models.CharField(blank=True, max_length=100, null=True)),
                ('total_pembayaran', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Mencari Pekerja Terdekat', 'Mencari Pekerja Terdekat'), ('Pesanan Selesai', 'Pesanan Selesai')], default='Menunggu Pembayaran', max_length=50)),
                ('pekerja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jasa.pekerja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jasa.sesilayanan')),
            ],
        ),
        migrations.CreateModel(
            name='Subkategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jasa.kategori')),
            ],
        ),
        migrations.AddField(
            model_name='sesilayanan',
            name='subkategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jasa.subkategori'),
        ),
    ]
